---
- name: Alterar porta SSH para 10022
  hosts: all
  become: yes
  tasks:
    - name: Alterar a configuração da porta no sshd_config
    become: yes
    lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Port '
    line: 'Port 10022'
    state: present
    backup: yes

    - name: Reiniciar o serviço SSH (Debian)
      service:
        name: ssh
        state: restarted
      when: ansible_facts['os_family'] == "Debian"

    - name: Reiniciar o serviço SSH (RedHat)
      service:
        name: sshd
        state: restarted
      when: ansible_facts['os_family'] == "RedHat"
